rubric = [
                {
                    "criterion": "Correctness",
                    "description": "Evaluates if the response contains accurate information and correct answers.",
                    "score_1": "Completely incorrect, with many factual errors.",
                    "score_2": "Mostly incorrect, with some correct information but many inaccuracies.",
                    "score_3": "Partially correct, with a mix of accurate and inaccurate information.",
                    "score_4": "Mostly correct, with only minor errors.",
                    "score_5": "Completely correct, with accurate and reliable information throughout.",
                },
                {
                    "criterion": "Entailment",
                    "description": "Measures if the response logically follows from the question or prompt.",
                    "score_1": "No logical connection to the question or prompt.",
                    "score_2": "Limited entailment, with several statements that do not logically follow.",
                    "score_3": "Moderate entailment, with some minor gaps in logic.",
                    "score_4": "Strong entailment, with only minor logical inconsistencies.",
                    "score_5": "Perfect entailment, with a clear and logical progression throughout.",
                },
                {
                    "criterion": "Completeness",
                    "description": "Assesses if the response fully addresses all aspects of the question or prompt.",
                    "score_1": "Very incomplete, missing most required information.",
                    "score_2": "Lacks several key points, leaving the response partially incomplete.",
                    "score_3": "Addresses the main points but misses some details.",
                    "score_4": "Mostly complete, covering most points with minor omissions.",
                    "score_5": "Fully complete, covering all points and details comprehensively.",
                },
                {
                    "criterion": "Coherence",
                    "description": "Measures if the response is logically structured and easy to follow.",
                    "score_1": "Very disjointed, with a lack of logical flow.",
                    "score_2": "Somewhat coherent, but difficult to follow at times.",
                    "score_3": "Moderately coherent, with occasional issues in flow.",
                    "score_4": "Mostly coherent, with only minor structural issues.",
                    "score_5": "Very coherent, with a logical and easy-to-follow structure.",
                },
                {
                    "criterion": "Relevance",
                    "description": "Assesses if the response stays on topic and directly addresses the question.",
                    "score_1": "Completely off-topic and irrelevant.",
                    "score_2": "Somewhat relevant but includes significant off-topic content.",
                    "score_3": "Mostly relevant, with some minor off-topic content.",
                    "score_4": "Very relevant, with only minor deviations from the topic.",
                    "score_5": "Highly relevant, directly addressing the question with no irrelevant content.",
                },
                {
                    "criterion": "Fairness (No Bias)",
                    "description": "Evaluates if the response is fair, balanced, and free from bias.",
                    "score_1": "Highly biased and unfair, with noticeable prejudice or favoritism.",
                    "score_2": "Somewhat biased, with moderate signs of partiality.",
                    "score_3": "Mostly fair, with minor instances of bias.",
                    "score_4": "Fair and unbiased, with very minor issues.",
                    "score_5": "Completely fair and unbiased, showing no signs of prejudice.",
                },
                {
                    "criterion": "Explainability",
                    "description": "Assesses if the response clearly explains the reasoning or information provided.",
                    "score_1": "No explanation provided, or explanation is incomprehensible.",
                    "score_2": "Limited explanation, with several unclear points.",
                    "score_3": "Moderate explanation, but some areas lack clarity.",
                    "score_4": "Mostly well-explained, with minor ambiguities.",
                    "score_5": "Highly explainable, with clear and thorough explanations.",
                },
                {
                    "criterion": "Helpfulness",
                    "description": "Evaluates if the response provides useful and actionable information.",
                    "score_1": "Not helpful, with no actionable or useful content.",
                    "score_2": "Limited helpfulness, with some useful information but lacking overall.",
                    "score_3": "Moderately helpful, with some actionable advice.",
                    "score_4": "Helpful, with valuable information and actionable points.",
                    "score_5": "Highly helpful, with comprehensive and actionable advice.",
                },
                {
                    "criterion": "Informativeness",
                    "description": "Measures if the response provides detailed and valuable information.",
                    "score_1": "Very uninformative, with minimal or irrelevant information.",
                    "score_2": "Limited informativeness, lacking depth and detail.",
                    "score_3": "Moderately informative, covering main points but lacking depth.",
                    "score_4": "Informative, with substantial details.",
                    "score_5": "Highly informative, with comprehensive and in-depth information.",
                }
            ]